# JRE base
FROM eclipse-temurin:17-jre-alpine

# Environment variables
ENV MC_VERSION="latest" \
    PAPER_BUILD="latest" \
    MC_RAM="" \
    JAVA_OPTS=""

COPY papermc.sh .
RUN apk -U upgrade && \
    apk -U add --no-cache tzdata curl wget jq && \
    rm -rf /tmp/* && rm -rf /var/cache/apk/* && \
    mkdir /papermc


# Start script
CMD ["sh", "./papermc.sh"]

# Container setup
EXPOSE 25565/tcp
EXPOSE 25565/udp
VOLUME /papermc
