name: Docker Image CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository_owner }}/papermc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Prepare Docker tags
      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      # https://github.com/docker/build-push-action
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.adoptium
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

